---
title: "Bem vindo ao website do Workshop de Introdução ao R"
---

Este workshop foi desenvolvido para o grupo de pesquisa Relações Internacionais e Ciência, Tecnologia e Inovação da UFSC.

### O que você encontrará neste site?
Neste site está disponível todo o material desenvolvido para o curso. Na aba "Workshops" estão os roteiros dos workshops com os respectivos códigos. Em "Repositório" você encontra o repositório do Github deste workshop com o material utilizado.

### Sobre a instrutora
Já tivemos a oportunidade de nos conhecer mas me apresento novamente. Meu nome é Natalia Block, cientista de dados com atuação no Brasil e nos EUA. Antes de migrar para a carreira de cientista de dados atuei como cientista política desenvolvendo pesquisa na academia e no setor privado e dando suporte à gestão de programas em organizações não governamentais. 

### Leia a página "Instruções para o Workshop" antes do nosso primeiro encontro. 
Lá você encontrará orientações importantes para acompanhar os workshops.  

### Tenha o R e o RStudio instalados no seu computador antes do primeiro workshop.
As instruções de instalação estão na página "Instruções para o Workshop".

### Calendários dos Workshops
Os workshops ocorrerão no horário de 19 às 21:15 nos seguintes dias:

  * 26/01/2021: Workshop 1
  * 02/02/2021: Workshop 2
  * 09/02/2021: Workshop 3
  * 23/02/2021 (depois do Carnaval): Workshop 4

